### PR TITLE
RFC: Moving around stuff

### PR DESCRIPTION
**Pull request by MindTooth**
I've not completely landed yet.  A bit unsure about the best way to rename those.

## Reasoning 

The reason I want a good reference, is if one is using a fuzzy finder, or simply searching for the file — which in that case, we might want to include the name in the file.

## Suggestion #&#xfeff;1

**Style in the current PR.**
Thought maybe I would also add a small readme in all folder on how to using the colors, if need to change name, etc.

Style in PR:
```
alacritty/alacritty.colors
gnome-terminal/gnome-terminal.colors
kitty/kitty.colors
...
```

## Suggestion \#&#xfeff;2

Or simply just use the folder as the name/reference to the specific application, and try to make sure the ending is correct for each app.

E.g:
```
alacritty/srcery.yml
gnome-terminal/srcery.sh
kitty/srcery.conf
...
```

### Unrelated
Not sure what `linux_console` is for?  Can't say a recognise the escape sequences.

### CODE REVIEW

**Comment by roosta** [comment]
I'm more partial to the second suggestion, I like having vim set the filetype without resorting to a modeline. As for the name of the scripts I recall an issue [here](https://github.com/roosta/vim-srcery/issues/5) where a user wasn't able to open the scheme by clicking on the file without it being named Terminal.app. That being said I don't use mac machines, so I don't really know if this is a limitation or not. I suppose we could add some instructions like you suggested if this is a problem.

the linux_console script is for the [virtual console](https://wiki.archlinux.org/index.php/Color_output_in_console#Virtual_console)

**Comment by MindTooth** [comment]
Yes, I concur.  The second version is the best.

I'll look at it tomorrow, and report back.

**Comment by MindTooth** [comment]
Couldn't stay away, so here is the next take :)

Converted the Chrome Secure Shell to a valid JavaScript file as showed [here](https://gist.github.com/jmoreman/6498207).

**Comment by roosta** [comment]
Looks good to me. I say we merge this :)

**Pull request merged**
